config/routes.rb
SglTimer::Application.routes.draw do

  root :to => 'timer#index'
  get "login/index"
    

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in" 

  get "timer" => "timer#index", :as => :timer
  post "timer" => "timer#create", :as => :timer
  put "timer" => "timer#update", :as => :timer

  resources :times
  resources :sessions
  resources :employees
  resources :projects

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id               :integer         not null, primary key
#  username         :string(255)
#  password_digest  :string(255)
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#  current_timer_id :integer
#

class Employee < ActiveRecord::Base
  #attr_accessor :password, :password_conformation
  attr_accessible :username, :password, :password_confirmation, :times_attributes
  has_many :times, :class_name => Times
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :username

  def clocked_in?
    current_timer_id != nil
  end

  def total_project_time(project_id)
    times.where(:project_id => project_id).map(&:total_time).sum.round(2)
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  due_date          :datetime
#  git_repo          :string(255)
#  description       :text
#  git_master_branch :string(255)
#

class Project < ActiveRecord::Base
  attr_accessible :name, :total_time, :times_attributes, :due_date_string, :due_date, :git_repo, :description, :git_master_branch
  attr_reader :due_date_string

  has_many :times, :class_name => Times

  #Employees on a project
  def employees
    times.map(&:employee).uniq
  end

  def my_time(employee)
    times.where(:employee_id => employee.id).map(&:total_time).sum.round(2)
  end 
  def total_time
    times.map(&:total_time).sum.round(2)
  end

  def due_date_string=(date)
    self.due_date = Chronic.parse(date.to_s)
  end
  def due_date_string
    self.due_date.strftime("%m/%d/%Y") if self.due_date
  end
  def due_date
    if super
      return super
    else
      return Time.now
    end
  end
end

app/models/times.rb
# == Schema Information
#
# Table name: times
#
#  id           :integer         not null, primary key
#  clock_in     :datetime
#  clock_out    :datetime
#  time_decimal :decimal(, )
#  employee_id  :integer
#  project_id   :integer
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  notes        :text
#

class Times < ActiveRecord::Base
  attr_accessible :clock_in, :clock_out, :employee_id, :project_id, :time_decimal, :notes, :total_time
  belongs_to :employee
  belongs_to :project
  validates :project_id, :presence => true
  validates :employee_id, :presence => true

  def clocked_in?
    clock_in != nil && clock_out == nil
  end

  def total_time_decimal
    unless clocked_in?
      return clock_out - clock_in 
    else
      return Time.now - clock_in
    end
  end

  def total_time=(time)
    #ajust time out
    self.clock_out = self.clock_in + (time.to_f* 3600)
    #save time in decimal
    self.time_decimal=time
  end

  def to_milliseconds
    (total_time_decimal.to_f/3600.to_i).round(2)* 3600000
  end

  def total_time
    total_time_hours_decimal
  end
  def total_time_hours_decimal
    (total_time_decimal.to_f/3600.to_i).round(2)
  end

  def total_time_display
    Time.at(total_time_decimal).gmtime.strftime('%R:%S')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def authenicate
    unless current_user
      redirect_to log_in_path, :alert => "Please login!"
    end
  end
  def current_user
    if session[:employee_id]
      @current_user ||= Employee.find(session[:employee_id])
    end
  end
  helper_method :current_user
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :authenicate

  def index
    @employees = Employee.all
  end
  def edit
    @employee = Employee.find(params[:id])
  end
  def new
    @employee = Employee.new
  end
  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      redirect_to employees_path, :notice => "Employee was successfully updated"
    end
  end
  def create
    @employee = Employee.new(params[:employee])
    if @employee.save 
      redirect_to employees_path, :notice => "Employee successfully created"
    else
      render "new"
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenicate
  def index
    @projects = Project.all
  end
  def new
    @project = Project.new
  end
  def show
    @project = Project.find(params[:id])
    unless @project.due_date_string
      @project.due_date_string = Time.now
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])
    redirect_to :back, :notice => "Successfully update the project info"
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to projects_path, :notice => "Successfully created project #{@project.name}"
    else
      render "new"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    employee = Employee.find_by_username(params[:username])
    if employee && employee.authenticate(params[:password])
      session[:employee_id] = employee.id
      redirect_to timer_path, :alert => "Logged in"
    else
      flash.now[:alert] = "Invalid username or password"
      render "new"
    end
  end
  def destroy 
    session[:employee_id] = nil
    session[:timer_id] = nil
    redirect_to log_in_path, :alert => "You are now logged out!"
  end
end

app/controllers/timer_controller.rb
class TimerController < ApplicationController
  before_filter :authenicate

  def index
    if current_user.current_timer_id
      @timer = Times.find(current_user.current_timer_id)
      @timer.notes.strip
    else
      @timer = Times.new(:notes => cookies[:notes], :project_id => cookies[:project_id])
    end
    @projects = Project.all
    @project = @timer.project unless @timer.new_record?
  end
  def update
    @timer = current_user.times.find(params[:times][:id])
    unless @timer.clock_out 
      @timer.clock_out = Time.now
    end
    @timer.notes = params[:times][:notes]
    @timer.save
    current_user.current_timer_id = nil
    current_user.save
    redirect_to timer_path, :notice => "Stopped Time on #{@timer.project.name}"
  end
  def create
    @timer = current_user.times.new(params[:times])
    @timer.notes = params[:times][:notes].strip
    @timer.clock_in = Time.now
    if @timer.save
      cookies[:project_id] = @timer.project_id
      cookies[:notes] = @timer.notes

      current_user.current_timer_id = @timer.id
      current_user.save
      redirect_to timer_path, :notice => "Started #{@timer.project.name}" 
    else
      redirect_to timer_path, :notice => "That did not work!" 
    end
  end
end

app/controllers/times_controller.rb
class TimesController < ApplicationController
  before_filter :authenicate
  def update 
    times = Times.find(params[:id])
    times.update_attributes(params[:times])
    times.save
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    messages = ""
    [:notice, :info, :warning, :error, :alert].each do |type|
      if flash[type]
        messages += content_tag :div, flash[type], :class => "#{type}", :id => "alert"
      end
    end 
    messages.html_safe
  end
  def clocked_in_class
    if current_user
      if current_user.clocked_in?
        "clocked_in"
      else
        "clocked_out"
      end
    end
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/timer_helper.rb
module TimerHelper
end

app/views/employees/_form.html.haml
=f.input :username, :label => "Username"
=f.input :password, :label => "Password"
=f.input :password_confirmation, :label => "Confirm Password"

app/views/employees/edit.html.haml
%h1 Edit Employee

=simple_form_for @employee do |f|
  =render :partial => 'employees/form', :locals => {:f => f}
  =f.button :submit, "Update"

app/views/employees/index.html.haml
%h1 Employees

%table
  %tr
    %th username
    %th actions
  -@employees.each do |employee|
    %tr
      %td= employee.username
      %td= link_to "Edit", edit_employee_path(employee)
=link_to "Add Employee", new_employee_path

app/views/employees/new.html.haml
%h1 New Employee

=simple_form_for @employee do |f|
  =render :partial => 'employees/form', :locals => {:f => f}
  =f.button :submit, "Create"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SglTimer</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= params[:controller] %> <%= clocked_in_class %>">
    <%= flash_message %>
    <% if current_user %>
      <div class="nav">
        <%=link_to "Home", timer_path %>
        <%=link_to "Projects", projects_path %>
        <%=link_to "Employees", employees_path %>
        <%=link_to "Log Out", log_out_path %> 
      </div>
    <% end %>
    <%= yield %>
    <div class="forkme">
      <%= link_to "Fork me on GitHub!", "https://github.com/priceflex/fuzzy-octo-timer" %>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<h1>Login#index</h1>
<p>Find me in app/views/login/index.html.erb</p>

app/views/projects/index.html.haml
%h1 Projects

%table
  %tr
    %th Name
    %th Time Left
    %th Action
  -@projects.each do |project|
    %tr
      %td= project.name
      %td= distance_of_time_in_words_to_now project.due_date
      %td
        = link_to "Show Details", project
= link_to "Create New Project", new_project_path

app/views/projects/new.html.haml
%h1 New Project

=simple_form_for @project do |f|
  =f.input :name
  =f.button :submit, "Create"

app/views/projects/show.html.haml
%h1
  Project:
  = @project.name

Time Left:
= distance_of_time_in_words_to_now @project.due_date
=simple_form_for @project do |f|
  =f.input :due_date_string, :label => "Project Due Date", :as => :string
  =f.input :git_repo
  =f.input :git_master_branch
  =f.input :description
  =f.button :submit, "Update"

%p
  Project Details
  %br
  Your Time:
  = @project.my_time(current_user)

Employees:
%ul
  -@project.employees.each do |employee|
    %li
      =employee.username
      |
      =employee.total_project_time(@project.id)

  = render :partial => "shared/project_table"

app/views/shared/_project_table.html.haml
.project_times
  %p 
    Total Time:
    =@project.total_time if @project
  %table
    %tr
      %th user
      %th date
      %th notes
      %th hours
      %th decimal
      %th action
    -@project.times.order("id desc").each do |time|
      -unless time.clocked_in?
        = render :partial => 'timer/times', :locals => {:time => time}
      -else
        = render :partial => 'timer/read_times', :locals => {:time => time}

app/views/timer/_read_times.html.haml
%tr{:class => ("clocked_in" if time.clocked_in?).to_s + " " +cycle("odd","even") }
  %td= time.employee.username
  %td= time.created_at.to_s(:stand_date)
  %td{:class => "notes"}
    = time.notes
  %td= time.total_time_display
  %td{:class => "decimal"}
    = time.total_time
  %td

app/views/timer/_times.html.haml
%tr{:class => ("clocked_in" if time.clocked_in?).to_s + " " + cycle("odd","even") }
  =simple_form_for time do |f|
    %td= time.employee.username
    %td= time.created_at.to_s(:stand_date)
    %td{:class => "notes"}
      = f.input :notes, :label_html => {:hidden => true}
    %td= time.total_time_display
    %td{:class => "decimal"}
      = f.input :total_time, :label_html => {:hidden => true} 
    %td= f.button :submit, "Update"

app/views/timer/index.html.haml
%h3 SGL Project Timer

=simple_form_for @timer, :url => timer_path do |f|
  -if @timer.clocked_in?
    ="Project: #{@timer.project.name}"
    .timer
      .hide
        #start_time
          =@timer.to_milliseconds.to_i
      #stopwatch
      :javascript 
        $(document).ready(function() { 
        var start_time = parseInt($("#start_time").text());
        $("#stopwatch").stopwatch({
        startTime: start_time,
        format: '{hh}:{mm}:{ss}'}).stopwatch('start');});
  -else
    =f.input :project_id, :collection => @projects, :prompt => "Select your project"
  =f.input :notes
  -if @timer.clocked_in?
    =f.button :submit, "Stop"
    =f.input :id, :as => :hidden
  -else
    =f.button :submit, "Start"

-if @project
  = render :partial => 'shared/project_table'